Us10 kara
sofiabrown91/team-elite-sprint2 pull request #3
Opened 2024-03-19 18:56 UTC by Karshyga1985

2024-03-19 18:59 UTC, celiker57 approved these changes
Looks all good. Good work Kara.

2024-03-19 19:18 UTC, Mykola2024 commented on src/test/resources/features/login.feature
> +    #Given the user logged in as "<userType>"
Why are you commenting out this step?
I am using this in my feature file

2024-03-19 19:21 UTC, Mykola2024 commented on src/test/resources/features/US_10.feature
Can you rename your Feature file and stepDefs file to follow our naming convetion
![Screenshot 2024-03-19 at 3 20 40 PM](https://github.com/sofiabrown91/team-elite-sprint2/assets/146555046/af4f0b46-0fd4-49ec-b5d8-7f295d8731ea)

2024-03-19 19:23 UTC, Mykola2024 requested changes
Please address comments.

2024-03-20 01:24 UTC, Mykola2024 approved these changes

2024-03-20 01:26 UTC, merged